/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testJFrame.java
 *
 * Created on Jan 9, 2009, 3:38:21 PM
 */

package test;

/**
 *
 * @author patrick.nelson
 */
public class testJFrame extends javax.swing.JFrame {

    /** Creates new form testJFrame */
    public testJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jSeparator1 = new javax.swing.JSeparator();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JSeparator();
    jMenuItem4 = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuItem6 = new javax.swing.JMenuItem();
    jSeparator3 = new javax.swing.JSeparator();
    jMenuItem7 = new javax.swing.JMenuItem();
    jMenuItem8 = new javax.swing.JMenuItem();
    jSeparator4 = new javax.swing.JSeparator();
    jMenuItem9 = new javax.swing.JMenuItem();
    jMenuItem10 = new javax.swing.JMenuItem();
    jMenuItem11 = new javax.swing.JMenuItem();
    jMenuItem12 = new javax.swing.JMenuItem();
    jMenuItem13 = new javax.swing.JMenuItem();
    jMenuItem14 = new javax.swing.JMenuItem();
    jSeparator5 = new javax.swing.JSeparator();
    jMenu3 = new javax.swing.JMenu();
    jSeparator6 = new javax.swing.JSeparator();
    jMenuItem15 = new javax.swing.JMenuItem();
    jMenuItem16 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem17 = new javax.swing.JMenuItem();
    jMenuItem18 = new javax.swing.JMenuItem();
    jSeparator7 = new javax.swing.JSeparator();
    jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
    jSeparator8 = new javax.swing.JSeparator();
    jMenuItem21 = new javax.swing.JMenuItem();
    jMenuItem22 = new javax.swing.JMenuItem();
    jMenuItem23 = new javax.swing.JMenuItem();
    jMenuItem24 = new javax.swing.JMenuItem();
    jMenuItem25 = new javax.swing.JMenuItem();
    jMenuItem26 = new javax.swing.JMenuItem();
    jSeparator9 = new javax.swing.JSeparator();
    jMenuItem27 = new javax.swing.JMenuItem();
    jMenuItem28 = new javax.swing.JMenuItem();
    jSeparator10 = new javax.swing.JSeparator();
    jMenuItem29 = new javax.swing.JMenuItem();
    jMenuItem30 = new javax.swing.JMenuItem();
    jMenuItem31 = new javax.swing.JMenuItem();
    jMenu4 = new javax.swing.JMenu();
    jMenuItem19 = new javax.swing.JMenuItem();
    jMenuItem20 = new javax.swing.JMenuItem();
    jSeparator11 = new javax.swing.JSeparator();
    jMenuItem32 = new javax.swing.JMenuItem();
    jMenuItem33 = new javax.swing.JMenuItem();
    jSeparator12 = new javax.swing.JSeparator();
    jMenuItem34 = new javax.swing.JMenuItem();
    jMenuItem35 = new javax.swing.JMenuItem();
    jSeparator13 = new javax.swing.JSeparator();
    jMenuItem36 = new javax.swing.JMenuItem();
    jSeparator14 = new javax.swing.JSeparator();
    jMenu5 = new javax.swing.JMenu();
    jMenuItem56 = new javax.swing.JMenuItem();
    jSeparator23 = new javax.swing.JSeparator();
    jMenuItem57 = new javax.swing.JMenuItem();
    jMenuItem58 = new javax.swing.JMenuItem();
    jSeparator24 = new javax.swing.JSeparator();
    jMenuItem59 = new javax.swing.JMenuItem();
    jMenu6 = new javax.swing.JMenu();
    jMenuItem60 = new javax.swing.JMenuItem();
    jSeparator25 = new javax.swing.JSeparator();
    jMenuItem61 = new javax.swing.JMenuItem();
    jMenuItem62 = new javax.swing.JMenuItem();
    jMenuItem63 = new javax.swing.JMenuItem();
    jSeparator26 = new javax.swing.JSeparator();
    jMenuItem64 = new javax.swing.JMenuItem();
    jMenuItem39 = new javax.swing.JMenuItem();
    jMenuItem40 = new javax.swing.JMenuItem();
    jMenuItem41 = new javax.swing.JMenuItem();
    jMenu7 = new javax.swing.JMenu();
    jMenuItem37 = new javax.swing.JMenuItem();
    jMenuItem38 = new javax.swing.JMenuItem();
    jMenuItem42 = new javax.swing.JMenuItem();
    jMenuItem43 = new javax.swing.JMenuItem();
    jSeparator15 = new javax.swing.JSeparator();
    jMenu8 = new javax.swing.JMenu();
    jCheckBoxMenuItem19 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem20 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem21 = new javax.swing.JCheckBoxMenuItem();
    jSeparator27 = new javax.swing.JSeparator();
    jCheckBoxMenuItem22 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem23 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem24 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem25 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem26 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem27 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem28 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem29 = new javax.swing.JCheckBoxMenuItem();
    jMenuItem44 = new javax.swing.JMenuItem();
    jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
    jSeparator16 = new javax.swing.JSeparator();
    jMenuItem46 = new javax.swing.JMenuItem();
    jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
    jSeparator17 = new javax.swing.JSeparator();
    jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
    jSeparator18 = new javax.swing.JSeparator();
    jMenuItem45 = new javax.swing.JMenuItem();
    jMenu9 = new javax.swing.JMenu();
    jMenuItem47 = new javax.swing.JMenuItem();
    jMenuItem48 = new javax.swing.JMenuItem();
    jSeparator19 = new javax.swing.JSeparator();
    jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem13 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem14 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem15 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem16 = new javax.swing.JCheckBoxMenuItem();
    jCheckBoxMenuItem17 = new javax.swing.JCheckBoxMenuItem();
    jSeparator20 = new javax.swing.JSeparator();
    jCheckBoxMenuItem18 = new javax.swing.JCheckBoxMenuItem();
    jMenuItem49 = new javax.swing.JMenuItem();
    jMenu10 = new javax.swing.JMenu();
    jMenuItem50 = new javax.swing.JMenuItem();
    jSeparator21 = new javax.swing.JSeparator();
    jMenuItem51 = new javax.swing.JMenuItem();
    jMenu11 = new javax.swing.JMenu();
    jMenuItem52 = new javax.swing.JMenuItem();
    jMenuItem53 = new javax.swing.JMenuItem();
    jMenuItem54 = new javax.swing.JMenuItem();
    jSeparator22 = new javax.swing.JSeparator();
    jMenuItem55 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jMenu1.setText("File");
    jMenu1.add(jSeparator1);

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem1.setText("Compare files...");
    jMenu1.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Select files...");
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("Compare folders...");
    jMenu1.add(jMenuItem3);
    jMenu1.add(jSeparator2);

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Print...");
    jMenu1.add(jMenuItem4);

    jMenuItem5.setText("Print preview");
    jMenu1.add(jMenuItem5);

    jMenuItem6.setText("Print options...");
    jMenu1.add(jMenuItem6);
    jMenu1.add(jSeparator3);

    jMenuItem7.setText("Report...");
    jMenu1.add(jMenuItem7);

    jMenuItem8.setText("Statistics");
    jMenu1.add(jMenuItem8);
    jMenu1.add(jSeparator4);

    jMenuItem9.setText("Save source");
    jMenu1.add(jMenuItem9);

    jMenuItem10.setText("Save destination");
    jMenu1.add(jMenuItem10);

    jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem11.setText("Save all");
    jMenu1.add(jMenuItem11);

    jMenuItem12.setText("Save as...");
    jMenu1.add(jMenuItem12);

    jMenuItem13.setText("Replace right file");
    jMenu1.add(jMenuItem13);

    jMenuItem14.setText("Save as result");
    jMenu1.add(jMenuItem14);
    jMenu1.add(jSeparator5);

    jMenu3.setText("Recent");
    jMenu1.add(jMenu3);
    jMenu1.add(jSeparator6);

    jMenuItem15.setText("Close all");
    jMenu1.add(jMenuItem15);

    jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    jMenuItem16.setText("Exit");
    jMenu1.add(jMenuItem16);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
    jMenuItem17.setText("Edit mode");
    jMenu2.add(jMenuItem17);

    jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem18.setText("Undo");
    jMenu2.add(jMenuItem18);
    jMenu2.add(jSeparator7);

    jCheckBoxMenuItem1.setSelected(true);
    jCheckBoxMenuItem1.setText("Source is editable");
    jMenu2.add(jCheckBoxMenuItem1);

    jCheckBoxMenuItem2.setSelected(true);
    jCheckBoxMenuItem2.setText("Target is editable");
    jMenu2.add(jCheckBoxMenuItem2);
    jMenu2.add(jSeparator8);

    jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem21.setText("Cut");
    jMenu2.add(jMenuItem21);

    jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem22.setText("Copy");
    jMenu2.add(jMenuItem22);

    jMenuItem23.setText("Copy diff");
    jMenu2.add(jMenuItem23);

    jMenuItem24.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem24.setText("Paste");
    jMenu2.add(jMenuItem24);

    jMenuItem25.setText("Select");
    jMenu2.add(jMenuItem25);

    jMenuItem26.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem26.setText("Select all");
    jMenu2.add(jMenuItem26);
    jMenu2.add(jSeparator9);

    jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem27.setText("Find");
    jMenu2.add(jMenuItem27);

    jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem28.setText("Replace");
    jMenu2.add(jMenuItem28);
    jMenu2.add(jSeparator10);

    jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem29.setText("Switch bookmark");
    jMenu2.add(jMenuItem29);

    jMenuItem30.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
    jMenuItem30.setText("Next bookmark");
    jMenu2.add(jMenuItem30);

    jMenuItem31.setText("Previous bookmark");
    jMenu2.add(jMenuItem31);

    jMenuBar1.add(jMenu2);

    jMenu4.setText("Merge");

    jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem19.setText("Copy >>");
    jMenu4.add(jMenuItem19);

    jMenuItem20.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem20.setText("Copy <<");
    jMenu4.add(jMenuItem20);
    jMenu4.add(jSeparator11);

    jMenuItem32.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_RIGHT, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem32.setText("Line to right");
    jMenu4.add(jMenuItem32);

    jMenuItem33.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LEFT, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem33.setText("Line to left");
    jMenu4.add(jMenuItem33);
    jMenu4.add(jSeparator12);

    jMenuItem34.setText("Insert before");
    jMenu4.add(jMenuItem34);

    jMenuItem35.setText("Insert after");
    jMenu4.add(jMenuItem35);
    jMenu4.add(jSeparator13);

    jMenuItem36.setText("Delete section");
    jMenu4.add(jMenuItem36);
    jMenu4.add(jSeparator14);

    jMenu5.setText("Manual");

    jMenuItem56.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem56.setText("Toggle Anchor");
    jMenu5.add(jMenuItem56);
    jMenu5.add(jSeparator23);

    jMenuItem57.setText("Show match");
    jMenu5.add(jMenuItem57);

    jMenuItem58.setText("Next anchor");
    jMenu5.add(jMenuItem58);
    jMenu5.add(jSeparator24);

    jMenuItem59.setText("Delete all anchors");
    jMenu5.add(jMenuItem59);

    jMenu4.add(jMenu5);

    jMenu6.setText("Ignore");

    jMenuItem60.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem60.setText("Toggle Ignore");
    jMenu6.add(jMenuItem60);
    jMenu6.add(jSeparator25);

    jMenuItem61.setText("Find first ignore");
    jMenu6.add(jMenuItem61);

    jMenuItem62.setText("Find next ignore");
    jMenu6.add(jMenuItem62);

    jMenuItem63.setText("Find previous ignore");
    jMenu6.add(jMenuItem63);
    jMenu6.add(jSeparator26);

    jMenuItem64.setText("Remove all");
    jMenu6.add(jMenuItem64);

    jMenu4.add(jMenu6);

    jMenuItem39.setText("Separate");
    jMenu4.add(jMenuItem39);

    jMenuItem40.setText("Show moved");
    jMenu4.add(jMenuItem40);

    jMenuItem41.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
    jMenuItem41.setText("Partial matching");
    jMenu4.add(jMenuItem41);

    jMenuBar1.add(jMenu4);

    jMenu7.setText("View");

    jMenuItem37.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
    jMenuItem37.setText("Next diff");
    jMenu7.add(jMenuItem37);

    jMenuItem38.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
    jMenuItem38.setText("Previous diff");
    jMenu7.add(jMenuItem38);

    jMenuItem42.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem42.setText("Next line diff");
    jMenu7.add(jMenuItem42);

    jMenuItem43.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem43.setText("Previous line diff");
    jMenu7.add(jMenuItem43);
    jMenu7.add(jSeparator15);

    jMenu8.setText("View as");

    jCheckBoxMenuItem19.setSelected(true);
    jCheckBoxMenuItem19.setText("Text");
    jMenu8.add(jCheckBoxMenuItem19);

    jCheckBoxMenuItem20.setText("Binary");
    jMenu8.add(jCheckBoxMenuItem20);

    jCheckBoxMenuItem21.setText("Image");
    jMenu8.add(jCheckBoxMenuItem21);
    jMenu8.add(jSeparator27);

    jCheckBoxMenuItem22.setText("Word");
    jMenu8.add(jCheckBoxMenuItem22);

    jCheckBoxMenuItem23.setText("Excel");
    jMenu8.add(jCheckBoxMenuItem23);

    jCheckBoxMenuItem24.setText("PDF");
    jMenu8.add(jCheckBoxMenuItem24);

    jCheckBoxMenuItem25.setText("MIF");
    jMenu8.add(jCheckBoxMenuItem25);

    jCheckBoxMenuItem26.setText("KOI");
    jMenu8.add(jCheckBoxMenuItem26);

    jCheckBoxMenuItem27.setText("CP866");
    jMenu8.add(jCheckBoxMenuItem27);

    jCheckBoxMenuItem28.setText("IFilter");
    jMenu8.add(jCheckBoxMenuItem28);

    jCheckBoxMenuItem29.setText("\\uXXXXX");
    jMenu8.add(jCheckBoxMenuItem29);

    jMenu7.add(jMenu8);

    jMenuItem44.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem44.setText("Go to line");
    jMenu7.add(jMenuItem44);

    jCheckBoxMenuItem4.setSelected(true);
    jCheckBoxMenuItem4.setText("Line numbers");
    jMenu7.add(jCheckBoxMenuItem4);
    jMenu7.add(jSeparator16);

    jMenuItem46.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem46.setText("Switch sides");
    jMenu7.add(jMenuItem46);

    jCheckBoxMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jCheckBoxMenuItem7.setSelected(true);
    jCheckBoxMenuItem7.setText("Horizontal view");
    jMenu7.add(jCheckBoxMenuItem7);

    jCheckBoxMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
    jCheckBoxMenuItem6.setSelected(true);
    jCheckBoxMenuItem6.setText("Word wrap");
    jMenu7.add(jCheckBoxMenuItem6);

    jCheckBoxMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
    jCheckBoxMenuItem5.setSelected(true);
    jCheckBoxMenuItem5.setText("Document wrap");
    jMenu7.add(jCheckBoxMenuItem5);

    jCheckBoxMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
    jCheckBoxMenuItem3.setSelected(true);
    jCheckBoxMenuItem3.setText("White space");
    jMenu7.add(jCheckBoxMenuItem3);

    jCheckBoxMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
    jCheckBoxMenuItem8.setSelected(true);
    jCheckBoxMenuItem8.setText("Syntax");
    jMenu7.add(jCheckBoxMenuItem8);

    jCheckBoxMenuItem9.setSelected(true);
    jCheckBoxMenuItem9.setText("Changes");
    jMenu7.add(jCheckBoxMenuItem9);

    jCheckBoxMenuItem10.setSelected(true);
    jCheckBoxMenuItem10.setText("Scroll lock");
    jMenu7.add(jCheckBoxMenuItem10);
    jMenu7.add(jSeparator17);

    jCheckBoxMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_MASK));
    jCheckBoxMenuItem11.setSelected(true);
    jCheckBoxMenuItem11.setText("Use fixed font");
    jMenu7.add(jCheckBoxMenuItem11);
    jMenu7.add(jSeparator18);

    jMenuItem45.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
    jMenuItem45.setText("Rescan");
    jMenu7.add(jMenuItem45);

    jMenuBar1.add(jMenu7);

    jMenu9.setText("Options");

    jMenuItem47.setText("Options...");
    jMenu9.add(jMenuItem47);

    jMenuItem48.setText("Toolbar...");
    jMenu9.add(jMenuItem48);
    jMenu9.add(jSeparator19);

    jCheckBoxMenuItem12.setSelected(true);
    jCheckBoxMenuItem12.setText("Tool bar");
    jMenu9.add(jCheckBoxMenuItem12);

    jCheckBoxMenuItem13.setSelected(true);
    jCheckBoxMenuItem13.setText("Status bar");
    jMenu9.add(jCheckBoxMenuItem13);

    jCheckBoxMenuItem14.setSelected(true);
    jCheckBoxMenuItem14.setText("Merge bar");
    jMenu9.add(jCheckBoxMenuItem14);

    jCheckBoxMenuItem15.setSelected(true);
    jCheckBoxMenuItem15.setText("Pane info");
    jMenu9.add(jCheckBoxMenuItem15);

    jCheckBoxMenuItem16.setSelected(true);
    jCheckBoxMenuItem16.setText("Overview");
    jMenu9.add(jCheckBoxMenuItem16);

    jCheckBoxMenuItem17.setSelected(true);
    jCheckBoxMenuItem17.setText("Lines view");
    jMenu9.add(jCheckBoxMenuItem17);
    jMenu9.add(jSeparator20);

    jCheckBoxMenuItem18.setSelected(true);
    jCheckBoxMenuItem18.setText("Move next");
    jMenu9.add(jCheckBoxMenuItem18);

    jMenuItem49.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.ALT_MASK));
    jMenuItem49.setText("Ignore nothing");
    jMenu9.add(jMenuItem49);

    jMenuBar1.add(jMenu9);

    jMenu10.setText("Tools");

    jMenuItem50.setText("Open");
    jMenu10.add(jMenuItem50);
    jMenu10.add(jSeparator21);

    jMenuItem51.setMnemonic('c');
    jMenuItem51.setText("Customize");
    jMenu10.add(jMenuItem51);

    jMenuBar1.add(jMenu10);

    jMenu11.setText("Help");

    jMenuItem52.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
    jMenuItem52.setText("Help");
    jMenu11.add(jMenuItem52);

    jMenuItem53.setText("Website");
    jMenu11.add(jMenuItem53);

    jMenuItem54.setText("Keys lists");
    jMenu11.add(jMenuItem54);
    jMenu11.add(jSeparator22);

    jMenuItem55.setText("About...");
    jMenu11.add(jMenuItem55);

    jMenuBar1.add(jMenu11);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 697, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 507, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testJFrame().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem13;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem14;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem15;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem16;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem17;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem18;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem19;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem20;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem21;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem22;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem23;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem24;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem25;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem26;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem27;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem28;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem29;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
  private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu10;
  private javax.swing.JMenu jMenu11;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenu jMenu3;
  private javax.swing.JMenu jMenu4;
  private javax.swing.JMenu jMenu5;
  private javax.swing.JMenu jMenu6;
  private javax.swing.JMenu jMenu7;
  private javax.swing.JMenu jMenu8;
  private javax.swing.JMenu jMenu9;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem10;
  private javax.swing.JMenuItem jMenuItem11;
  private javax.swing.JMenuItem jMenuItem12;
  private javax.swing.JMenuItem jMenuItem13;
  private javax.swing.JMenuItem jMenuItem14;
  private javax.swing.JMenuItem jMenuItem15;
  private javax.swing.JMenuItem jMenuItem16;
  private javax.swing.JMenuItem jMenuItem17;
  private javax.swing.JMenuItem jMenuItem18;
  private javax.swing.JMenuItem jMenuItem19;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem20;
  private javax.swing.JMenuItem jMenuItem21;
  private javax.swing.JMenuItem jMenuItem22;
  private javax.swing.JMenuItem jMenuItem23;
  private javax.swing.JMenuItem jMenuItem24;
  private javax.swing.JMenuItem jMenuItem25;
  private javax.swing.JMenuItem jMenuItem26;
  private javax.swing.JMenuItem jMenuItem27;
  private javax.swing.JMenuItem jMenuItem28;
  private javax.swing.JMenuItem jMenuItem29;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem30;
  private javax.swing.JMenuItem jMenuItem31;
  private javax.swing.JMenuItem jMenuItem32;
  private javax.swing.JMenuItem jMenuItem33;
  private javax.swing.JMenuItem jMenuItem34;
  private javax.swing.JMenuItem jMenuItem35;
  private javax.swing.JMenuItem jMenuItem36;
  private javax.swing.JMenuItem jMenuItem37;
  private javax.swing.JMenuItem jMenuItem38;
  private javax.swing.JMenuItem jMenuItem39;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem40;
  private javax.swing.JMenuItem jMenuItem41;
  private javax.swing.JMenuItem jMenuItem42;
  private javax.swing.JMenuItem jMenuItem43;
  private javax.swing.JMenuItem jMenuItem44;
  private javax.swing.JMenuItem jMenuItem45;
  private javax.swing.JMenuItem jMenuItem46;
  private javax.swing.JMenuItem jMenuItem47;
  private javax.swing.JMenuItem jMenuItem48;
  private javax.swing.JMenuItem jMenuItem49;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem50;
  private javax.swing.JMenuItem jMenuItem51;
  private javax.swing.JMenuItem jMenuItem52;
  private javax.swing.JMenuItem jMenuItem53;
  private javax.swing.JMenuItem jMenuItem54;
  private javax.swing.JMenuItem jMenuItem55;
  private javax.swing.JMenuItem jMenuItem56;
  private javax.swing.JMenuItem jMenuItem57;
  private javax.swing.JMenuItem jMenuItem58;
  private javax.swing.JMenuItem jMenuItem59;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem60;
  private javax.swing.JMenuItem jMenuItem61;
  private javax.swing.JMenuItem jMenuItem62;
  private javax.swing.JMenuItem jMenuItem63;
  private javax.swing.JMenuItem jMenuItem64;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuItem jMenuItem9;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator10;
  private javax.swing.JSeparator jSeparator11;
  private javax.swing.JSeparator jSeparator12;
  private javax.swing.JSeparator jSeparator13;
  private javax.swing.JSeparator jSeparator14;
  private javax.swing.JSeparator jSeparator15;
  private javax.swing.JSeparator jSeparator16;
  private javax.swing.JSeparator jSeparator17;
  private javax.swing.JSeparator jSeparator18;
  private javax.swing.JSeparator jSeparator19;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator20;
  private javax.swing.JSeparator jSeparator21;
  private javax.swing.JSeparator jSeparator22;
  private javax.swing.JSeparator jSeparator23;
  private javax.swing.JSeparator jSeparator24;
  private javax.swing.JSeparator jSeparator25;
  private javax.swing.JSeparator jSeparator26;
  private javax.swing.JSeparator jSeparator27;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JSeparator jSeparator5;
  private javax.swing.JSeparator jSeparator6;
  private javax.swing.JSeparator jSeparator7;
  private javax.swing.JSeparator jSeparator8;
  private javax.swing.JSeparator jSeparator9;
  // End of variables declaration//GEN-END:variables

}
